name: siklus_vita
description: Aplikasi SiklusVita (local DB)
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+3
  path_provider: ^2.0.14
  path: ^1.8.3
  shared_preferences: ^2.1.1
  percent_indicator: ^4.2.2
  table_calendar: ^3.0.6
  flutter_svg: ^1.1.6
